services:
    - docker
  
before_install: 
  - docker build -t alexeyca/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexeyca/docker-react-test npm run test -- --coverage

after_success:
  - docker build -t alexeyca/multi-client -f ./client
  - docker build -t alexeyca/multi-nginx -f ./nginx
  - docker build -t alexeyca/multi-server -f ./server
  - docker build -t alexeyca/multi-worker -f ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Upload images
  - docker push alexeyca/multi-client
  - docker push alexeyca/multi-nginx
  - docker push alexeyca/multi-server
  - docker push alexeyca/multi-worker
  