services:
    - docker
  
before_install: 
  - docker build -t alexeyca/docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexeyca/docker-react-test npm run test -- --coverage

after_success:
  - docker build -t alexeyca/multi-client ./client
  - docker build -t alexeyca/multi-nginx ./nginx
  - docker build -t alexeyca/multi-server ./server
  - docker build -t alexeyca/multi-worker ./worker
  # Log in to Docker CLI
  - echo "Deploying for "; echo "$DOCKER_ID"
  - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_ID" --password-stdin
  # Upload images
  - docker push alexeyca/multi-client
  - docker push alexeyca/multi-nginx
  - docker push alexeyca/multi-server
  - docker push alexeyca/multi-worker
